config/routes.rb
Rails.application.routes.draw do

  namespace :accounts do
    namespace :exam_answers do
      get 'error/index'
    end
    get 'exam_answers/index'
  end

  get 'exam_answers/create'

  get 'subjects/index'

  devise_for :admins
  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations',
                       passwords: 'users/passwords'
                   }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :exam_papers, only: [:index, :show] do
    resources :subjects, only: [:index]
    resources :exam_answers, only: [:create] do
      collection do
        get 'result'
      end
    end
  end

  root 'exam_papers#index'

end

app/models/exam_paper.rb
class ExamPaper < ActiveRecord::Base
  # PMP试卷
  has_many :subjects
  validates_presence_of :title

end

app/controllers/exam_papers_controller.rb
class ExamPapersController < ApplicationController
  before_action :authenticate_user!
  def index
    @exam_papers = ExamPaper.page(params[:page])
  end

  def show
    @exam_paper = ExamPaper.find_by_id(params[:id])
  end

  def new
  end

  def create
  end

end

app/helpers/exam_papers_helper.rb
module ExamPapersHelper
end

app/views/exam_papers/create.html.erb
<h1>ExamPapers#create</h1>
<p>Find me in app/views/exam_papers/create.html.erb</p>

app/views/exam_papers/index.html.erb
<div class="list-group">
  <% @exam_papers.each do |exam_paper|%>
    <div class="list-group-item">
      <div class="row-action-primary">
        <i class="material-icons">folder</i>
      </div>
      <%= link_to exam_paper_subjects_path(exam_paper) do %>
        <div class="row-content">
          <div class="action-secondary"><i class="material-icons">info</i></div>
          <h4 class="list-group-item-heading"><%= exam_paper.title%></h4>
        </div>
      <% end %>
    </div>
    <div class="list-group-separator"></div>
  <% end %>
</div>

app/views/exam_papers/new.html.erb
<h1>ExamPapers#new</h1>
<p>Find me in app/views/exam_papers/new.html.erb</p>