config/routes.rb
Rails.application.routes.draw do

  namespace :accounts do
    namespace :exam_answers do
      get 'error/index'
    end
    get 'exam_answers/index'
  end

  get 'exam_answers/create'

  get 'subjects/index'

  devise_for :admins
  devise_for :users, controllers: {
                       sessions: 'users/sessions',
                       registrations: 'users/registrations',
                       passwords: 'users/passwords'
                   }

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :exam_papers, only: [:index, :show] do
    resources :subjects, only: [:index]
    resources :exam_answers, only: [:create] do
      collection do
        get 'result'
      end
    end
  end

  root 'exam_papers#index'

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  # 考题
  belongs_to :exam_paper, counter_cache: true
  has_many :exam_options
  validates_presence_of :content, :exam_paper_id

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :exam_paper
  def index
    @subjects = Subject.where(exam_paper: @exam_paper).page(params[:page]).per(1)
  end

  private

  def exam_paper
    @exam_paper = ExamPaper.find_by_id(params[:exam_paper_id])
    if @exam_paper.blank?
      redirect_to root_path
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/index.html.erb
<div class="row">
  <% if @subjects.last_page?%>
    <%= link_to "查看结果", result_exam_paper_exam_answers_path(@exam_paper), class: "btn btn-lg btn-block btn-raised btn-danger"%>
  <% end %>
  <div class="col-md-12">
  <%= simple_form_for ExamAnswer.new, url: exam_paper_exam_answers_path(@exam_paper), remote: true do |f| %>
  <% @subjects.each do |subject|%>
    <%= f.hidden_field :subject_id, value: subject.id %>
      <fieldset>
        <div class="form-group is-empty">
            <h5><%= subject.content%></h5>
        </div>
        <div class="form-group is-empty">
          <% subject.exam_options.each do |option|%>
            <div class="radio radio-primary">
              <label>
                <input type="radio" name="exam_answer[exam_option_id]" id="exam_answer_exam_option_id" value="<%= option.id%>" >
                <p class="text-info"><%= option.title%></p>
              </label>
            </div>
          <% end %>
        </div>
      </fieldset>
    <% end %>
  <% end %>
  <ul class="pager">
    <%= link_to_previous_page @subjects, '上一题', class: 'btn btn-primary btn-lg btn-block btn-raised' %>
    <%= link_to_next_page @subjects, '下一题', class: 'btn btn-primary btn-lg btn-block btn-raised' %>
  </ul>
  </div>
</div>
<script>
  $(function () {
    $.material.init();
  });
  $('input[type=radio]').on('change', function() {
    $(this).closest("form").submit();
  });
</script>